"""Top-level handover orchestration.

Takes the WorkerResult + Brief, produces a deliverable according to
``brief.deliverable.type`` and routes the report according to ``report_to``.
"""
from __future__ import annotations

import logging
import shutil
import subprocess
import tarfile
from dataclasses import dataclass, field
from pathlib import Path

from teamnot.brief import Brief, DeliverableType, ReportTarget
from teamnot.delivery.git_branch import (
    create_feature_branch,
    diff_summary,
    push_branch,
)

logger = logging.getLogger("teamnot.delivery.handover")


@dataclass
class HandoverResult:
    ok: bool
    deliverable_type: str
    summary: str
    artifacts: dict = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)


# ── Top-level ────────────────────────────────────────────────────────────────

def handover(
    brief: Brief,
    *,
    success: bool,
    report_body: str,
    report_path: Path,
) -> HandoverResult:
    """Run the deliverable handover for the brief's configured type."""
    deliverable = brief.deliverable

    # 1. Code/files handover
    if deliverable.type == DeliverableType.feature_branch:
        r = _handover_feature_branch(brief, success)
    elif deliverable.type == DeliverableType.pull_request:
        r = _handover_pull_request(brief, success)
    elif deliverable.type == DeliverableType.tarball:
        r = _handover_tarball(brief)
    elif deliverable.type == DeliverableType.files:
        r = _handover_files(brief)
    elif deliverable.type == DeliverableType.report_only:
        r = HandoverResult(ok=True, deliverable_type="report_only",
                           summary="no code handover requested")
    else:
        r = HandoverResult(ok=False, deliverable_type=str(deliverable.type),
                           summary=f"unknown deliverable type: {deliverable.type}")

    # 2. Report routing
    routed = _route_report(brief, report_body, report_path)
    r.artifacts["report_routed_to"] = routed
    if routed:
        r.notes.append(f"report routed to {deliverable.report_to.value}")
    return r


# ── Implementations ──────────────────────────────────────────────────────────

def _handover_feature_branch(brief: Brief, success: bool) -> HandoverResult:
    branch = brief.deliverable.branch or f"feature/{brief.task.id.lower()}"
    commit_msg = f"TeamNoT [{brief.task.id}] {brief.task.title}"
    git = create_feature_branch(
        brief.project.path,
        branch=branch,
        base=brief.deliverable.base,
        commit_message=commit_msg if success else None,
    )
    notes: list[str] = []
    if not git.get("ok"):
        return HandoverResult(
            ok=False,
            deliverable_type="feature_branch",
            summary=f"branch creation failed: {git.get('error')}",
            notes=git.get("state", []),
        )

    diff = diff_summary(brief.project.path, brief.deliverable.base)
    push_info: dict | None = None
    if brief.deliverable.push_remote and success:
        push_info = push_branch(brief.project.path, branch)
        if not push_info.get("ok"):
            notes.append(f"push refused: {push_info.get('stderr', 'unknown')}")

    return HandoverResult(
        ok=True,
        deliverable_type="feature_branch",
        summary=f"branch `{branch}` ready (base={brief.deliverable.base})",
        artifacts={"git": git, "diff": diff, "push": push_info},
        notes=notes,
    )


def _handover_pull_request(brief: Brief, success: bool) -> HandoverResult:
    fb = _handover_feature_branch(brief, success)
    if not fb.ok or not success:
        return HandoverResult(
            ok=False,
            deliverable_type="pull_request",
            summary="branch failed; not opening PR",
            artifacts=fb.artifacts,
        )

    if not shutil.which("gh"):
        return HandoverResult(
            ok=False,
            deliverable_type="pull_request",
            summary="gh CLI not installed; branch ready but PR not opened",
            artifacts=fb.artifacts,
            notes=["install gh from https://cli.github.com to enable PR handover"],
        )

    branch = brief.deliverable.branch
    title = f"[{brief.task.id}] {brief.task.title}"
    body = f"Generated by TeamNoT.\n\nTask: {brief.task.title}\n\n{brief.task.description}"
    rc = subprocess.run(
        ["gh", "pr", "create", "--base", brief.deliverable.base,
         "--head", branch or "", "--title", title, "--body", body],
        cwd=str(brief.project.path),
        capture_output=True,
        text=True,
        timeout=120,
    )
    ok = rc.returncode == 0
    return HandoverResult(
        ok=ok,
        deliverable_type="pull_request",
        summary=rc.stdout.strip() if ok else "gh pr create failed",
        artifacts={**fb.artifacts, "gh_stdout": rc.stdout, "gh_stderr": rc.stderr},
    )


def _handover_files(brief: Brief) -> HandoverResult:
    diff = diff_summary(brief.project.path, brief.deliverable.base)
    return HandoverResult(
        ok=True,
        deliverable_type="files",
        summary=f"{len(diff.get('files', []))} file(s) changed",
        artifacts={"diff": diff},
    )


def _handover_tarball(brief: Brief) -> HandoverResult:
    diff = diff_summary(brief.project.path, brief.deliverable.base)
    files = diff.get("files", []) if diff.get("ok") else []
    if not files:
        return HandoverResult(
            ok=False,
            deliverable_type="tarball",
            summary="no changed files to pack",
            artifacts={"diff": diff},
        )
    out = brief.absolute(f".teamnot/reports/{brief.task.id}.tar.gz")
    out.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(out, "w:gz") as tf:
        for f in files:
            src = brief.absolute(f)
            if src.exists():
                tf.add(str(src), arcname=f)
    return HandoverResult(
        ok=True,
        deliverable_type="tarball",
        summary=f"packed {len(files)} files into {out.name}",
        artifacts={"tarball": str(out), "diff": diff},
    )


# ── Report routing ───────────────────────────────────────────────────────────

def _route_report(brief: Brief, body: str, source: Path) -> str | None:
    target = brief.deliverable.report_to
    if target == ReportTarget.stdout:
        return None  # CLI prints separately
    if target == ReportTarget.file:
        out = Path(brief.deliverable.report_path or
                   (brief.project.path / ".teamnot" / "reports" / f"{brief.task.id}__final.md"))
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8")
        return str(out)
    if target == ReportTarget.webhook:
        url = brief.deliverable.webhook_url
        if not url:
            logger.warning("report_to=webhook but webhook_url not set")
            return None
        try:
            import httpx
            r = httpx.post(url, json={"task_id": brief.task.id, "report": body}, timeout=30)
            return f"{url} (status={r.status_code})"
        except Exception as e:
            logger.warning("webhook POST failed: %s", e)
            return None
    if target == ReportTarget.telegram:
        # Telegram routing is owned by the telegram gateway — it picks up
        # final reports from .teamnot/reports/ and forwards them.
        chat = brief.deliverable.telegram_chat_id
        if not chat:
            logger.warning("report_to=telegram but telegram_chat_id not set")
            return None
        return f"telegram chat {chat} (handled by gateway)"
    return None
